dataset:
  base_dir: 'D:/SemanticKITTI/dataset/sequences'
  config: './config/semantic-kitti.yaml'

training_params:
  epochs: 40
  batch_size: 1
  num_classes: 20
  learning_rate: 0.01
  lr_decay_steps: 1000
  l2_reg: 0.001
  es_patience: 20
  n_node_features: 7
  lovasz_switch_ratio: 1.5
  feature_spec: 'xyz_i_rgb'