dataset:
  base_dir: 'D:/SemanticKITTI/dataset/sequences'
  config: './config/semantic-kitti.yaml'
#  base_dir: 'D:/vkitti3d_dataset_v1.0'
#  config: './config/vkitti.yaml'

training_params:
  epochs: 40
  batch_size: 1
  num_classes: 20
  learning_rate: 0.01
  lr_decay_steps: 1000
  l2_reg: 0.001
  es_patience: 20
  n_node_features: 6
  lovasz_switch_ratio: 0.3
  feature_spec: 'xyz_rgb'